### ISSUE TITLE
[collections]: add meta information to Articles

### ISSUE THREAD

**Issue by hunghvu** [hunghvu/hungvu.tech#2]
This meta information is not limited to search engine context, but also what makes an article "operable". Ignore input validation for now.
- [x] URL slug (move from page content to here)
- [x] SEO title
- [x] SEO description
- [x] Scheduled release date
- [x] Article status: Published, draft

- Generate the following two on the front end instead: Open Graph data, schema..org
